---
area/github:
- changed-files:
  - any-glob-to-any-file: ".github/**/*"
area/charts:
- changed-files:
  - any-glob-to-any-file: "charts/**/*"
area/docs:
- changed-files:
  - any-glob-to-any-file: "docs/**/*"
area/frontend:
- changed-files:
  - any-glob-to-any-file: "src/main/webui/**/*"
area/backend:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/main/**/*"
    - all-globs-to-all-files: '!src/main/webui/**/*'
area/test:
- changed-files:
  - any-glob-to-any-file: "src/test/**/*"
area/src:
- changed-files:
  - any-glob-to-any-file: "src/**/*"
