repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: mixed-line-ending
      # - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      # - id: check-yaml
        args: ["--allow-multiple-documents", "--unsafe"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: pretty-format-json
        args: ["--autofix", "--indent", "3", "--no-sort-keys"]
