---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: startpunkt-role
  labels:
    app.kubernetes.io/name: startpunkt
    app.kubernetes.io/version: 0.5.0
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list"]
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes"]
  verbs: ["get", "list"]
- apiGroups: ["forecastle.stakater.com"]
  resources: ["forecastleapps"]
  verbs: ["get", "list"]
- apiGroups: ["hajimari.io"]
  resources: ["applications", "bookmarks"]
  verbs: ["get", "list"]
- apiGroups: ["startpunkt.ullberg.us"]
  resources: ["applications", "bookmarks"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: startpunkt-rolebinding
  labels:
    app.kubernetes.io/name: startpunkt
    app.kubernetes.io/version: 0.5.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: startpunkt-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{.Release.Namespace}}
