---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "startpunkt.labels.chart" . | indent 4 }}
  name: {{ .Values.startpunkt.serviceAccountName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
