---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
{{ include "startpunkt.labels.chart" . | indent 4 }}
  name: {{ template "startpunkt.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.startpunkt.ports.http }}
  selector:
    app.kubernetes.io/name: {{ template "startpunkt.name" . }}
    app.kubernetes.io/version: {{ .Values.startpunkt.labels.version }}
  type: ClusterIP
