---
name: Meta - Labeler

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: Labeler
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
