---
name: Pull Requests Build

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    env:
      MVN: mvn --show-version --batch-mode
      CI: false

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: 🧹 Clean and Compile
        run: $MVN clean compile

      - name: 🧪 Run Tests
        run: $MVN test --batch-mode --fail-at-end

      - name: 📄 Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: true

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: 📡 SonarCloud Scan
        run: $MVN verify sonar:sonar -Dsonar.organization=magnus-ullberg -Dsonar.projectKey=magnus-ullberg_startpunkt -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 📦 Package Native Application
        run: $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: 🐋 Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
