name: Links

on:
  pull_request:
    branches:
    - main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - name: ⤵️ Check out code from GitHub
      uses: actions/checkout@v4

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1
