name: "Codeowners Validator"

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron:  '0 8 * * *'

jobs:
  codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.7.4
        # input parameters
        with:
          # github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
          checks: "files,duppatterns,syntax"
          experimental_checks: "notowned,avoid-shadowing"
